version: "3.9"
services:
  web:
    build: .
    container_name: cloud-file-versioning-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app/uploads:/app/app/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: cloud-file-versioning-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cfv_db
      MYSQL_USER: cfv_user
      MYSQL_PASSWORD: cfv_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
